// Shows every listitem
GET http://localhost:3000/api

###

// Shows the closest date for homeworks
GET http://localhost:3000/api/closest

###

// Add a item to the list
POST http://localhost:3000/api
Content-Type: application/json

    {
        "subject": "Historia",
        "pages": "Kapitel 6",
        "toDate": "2021-04-15"
    }

###

// Change an excisting item
PUT http://localhost:3000/api/5
Content-Type: application/json

    {
        "subject": "Svenska",
        "pages": "60-68",
        "toDate": "2021-04-29"
    }

###

// Deletes one item
DELETE http://localhost:3000/api/10

###

// Deletes all items
DELETE http://localhost:3000/api


