GET http://localhost:3000/api

###

GET http://localhost:3000/api/2

###

POST http://localhost:3000/api
Content-Type: application/json

    {
        "subject": "Naturorientering",
        "pages": "Kapitel 6",
        "toDate": 210425
    }

###

PUT http://localhost:3000/api
Content-Type: application/json

    {
        "subject": "Svenska",
        "pages": "60-68",
        "toDate": 210429,
        "id": 3
    }

###

DELETE http://localhost:3000/api
Content-Type: application/json

    {
        "id": 1
    }

